services:
  rabbitmq:
    image: rabbitmq:4-management-alpine
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 500ms
      timeout: 1s
      retries: 10
      start_period: 2s

  auth.macragge.ultramarines:
    image: nginx:alpine
    volumes:
      - ./auth.macragge.ultramarines.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://127.0.0.1/health || exit 1",
        ]
      interval: 1s
      timeout: 1s
      retries: 5

  auth.calth.ultramarines:
    image: nginx:alpine
    volumes:
      - ./auth.calth.ultramarines.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://127.0.0.1/health || exit 1",
        ]
      interval: 1s
      timeout: 1s
      retries: 5

  producer:
    build:
      context: ../..
      dockerfile: Dockerfile
      target: producer
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
      - IDP_URLS=["http://auth.macragge.ultramarines","http://auth.calth.ultramarines"]
      - QUEUE_PRODUCER_NAME=monitoring-producer
      - QUEUE_CONSUMER_NAME=monitoring-consumer
    depends_on:
      rabbitmq:
        condition: service_healthy
      auth.macragge.ultramarines:
        condition: service_healthy
      auth.calth.ultramarines:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://127.0.0.1/",
        ]
      interval: 1s
      timeout: 1s
      retries: 5

  consumer:
    build:
      context: ../..
      dockerfile: Dockerfile
      target: consumer
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672
      - QUEUE_PRODUCER_NAME=monitoring-producer
      - QUEUE_CONSUMER_NAME=monitoring-consumer
      - MAP_FI_NAMES_TO_URL={"macragge":"http://auth.macragge.ultramarines","calth":"http://auth.calth.ultramarines"}
    depends_on:
      rabbitmq:
        condition: service_healthy
      auth.macragge.ultramarines:
        condition: service_healthy
      auth.calth.ultramarines:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://127.0.0.1/health/ready",
        ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  test_runner:
    image: curlimages/curl:latest
    depends_on:
      - rabbitmq
      - auth.macragge.ultramarines
      - auth.calth.ultramarines
      - producer
      - consumer
    entrypoint: ["sleep", "infinity"]
